name: ubuntu-22.04-arm

on:
  push:
    paths-ignore:
      - images/*.cmd
      - README.md
      - LICENSE

jobs:
  ubuntu-2204-arm:
    uses: ./.github/workflows/ubuntu.yml
    with:
      ubuntu-version: 22.04
      arm64: true
      minimal: false
      slim: false
      instance: r7gd.large:ubuntu-24.04-arm-minimal:ap-south-1
